version: '3.9'
services:
  db:
    build: ./db/
    image: muratx10/database-psql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app
  node-app:
    build: ./
    image: muratx10/node-app
    networks:
      app:
        aliases:
          - db
    restart: always
    working_dir: /usr/app/
    env_file:
      - .env
    depends_on:
      - db
    ports:
    - ${PORT}:${PORT}
    volumes:
    - ./logs:/app/logs
    - ./src:/app/src
    - /app/node_modules

networks:
  app:
    driver: bridge
