version: '3.9'
services:
  db:
    image: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
    - ${POSTGRES_PORT}:5432
  nodejs:
    build: ./
    image: muratx10/docker-node
    networks:
      - app
#    command: bash -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all"
    restart: always
    working_dir: /usr/app/
    depends_on:
      - db
    ports:
    - ${PORT}:${PORT}
    volumes:
    - .:/usr/app
