version: '3.9'
services:
  db:
    build: ./db/
    image: muratx10/database-psql
    container_name: database-psql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/local:/var/lib/postgresql/data
    networks:
      - app
  node-app:
    build: ./
    image: muratx10/node-app
    container_name: node-app
    networks:
      app:
        aliases:
          - db
    restart: on-failure
    working_dir: /usr/app/
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    command: npm run start
    volumes:
      - ./log:/usr/app/log
      - ./src:/usr/app/src

networks:
  app:
    driver: bridge
