version: '3.9'
services:
  node-app:
    build: ./
    image: muratx10/node-app
    container_name: node-app
    networks:
      app:
    restart: on-failure
    working_dir: /usr/app/
    env_file:
      - .env
    depends_on:
      - db
    environment:
      HOST_PORT: ${HOST_PORT}
      CONTAINER_PORT: ${CONTAINER_PORT}
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    command: npm run start
    volumes:
      - ./log:/usr/app/log
      - ./src:/usr/app/src

  db:
    build: ./db/
    image: muratx10/database-psql
    container_name: database-psql
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/local:/var/lib/postgresql/data
    networks:
      app:
        aliases:
          - db

networks:
  app:
    driver: bridge
